run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - revive

linters-settings:
  goimports:
    local-prefixes: samasalaire-backend
  revive:
    rules:
      - name: var-naming
      - name: exported

issues:
  exclude-use-default: false
  max-same-issues: 50
